language: node_js
node_js:
  - '10'
  - '12'

notifications:
  email:
    on_success: never
    on_failure: always

script: yarn build

deploy:
  provider: npm
  email: npm@jupiterone.io
  api_key:
    secure: "k1G4/1NuSV586G0/shPjkuoopSiNatDp3TLT3KZzjMLf/qT/2px2cHaRyPqkVfeA5M7aA2m7Q6BotuG7BPTW4D5EdStGDS3GlmcAbqTwTm8sDVIqMyhi6M9R6Ao3yWC/0K7jmrvdHk5YDZuSwZzQpDcxYNtn6lP5asfIWYb2z1IMzJIuv7PQyFlCPImQLppqlDegb904aBWj4VtVjeio9L1U40ZYjgUNtwvBDyqb3/gIJcYEP1gxpBhVPs8NnaihYVntJpqS/WD+uetWV5n/nVrQCc5cyC7cG+SVfheG+DFxM3hWQ7w2MYA5AW7cY6PJxAlxn0s9DjN+2mOBmoWfDgbaszd7anVghAd6T0ZvG6K7P9W4H3AlcPRrOHw3dm7MYOel+j3yxTdgTZqqx0KjoWGYeFUXNAeWyPcgLe4f5fdyAT0uWG2CX/JCvSLw9V67Pk2ErBR/WNGkY3mGUvxR8goE4AMqXUezv+iigq0XSUDOKMEwShR8Ljun8zjgZ5nObREbugXuDPk+2S6KcaFG9lhOZiCXZvLL3IyhKE7JPJ7AlwHGk++jeUHz02RYLVJT/Afz1wZg7GREHYRDm2OOVkXlg0u5HHSWYe07LSOfepCmIRCoETi8wzkD25L/orQoHYkzegGKJh2p6d3coccLW1XskQSfsAz+kV9sJO2da/A="
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: JupiterOne/graph-google
    node: '12'
